// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY5L91wFepHKlkJk1cPwg86B2pcd4eOw8',
    appId: '1:814901029007:web:b766f88b2f10c2282b28fa',
    messagingSenderId: '814901029007',
    projectId: 'auth-app-riverpod',
    authDomain: 'auth-app-riverpod.firebaseapp.com',
    storageBucket: 'auth-app-riverpod.appspot.com',
    measurementId: 'G-HJKX4WZ9YQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO5M31L2D2GwBT6hjnp3wPNsPAXfK1F-Q',
    appId: '1:814901029007:android:2d0324ad7272ac682b28fa',
    messagingSenderId: '814901029007',
    projectId: 'auth-app-riverpod',
    storageBucket: 'auth-app-riverpod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAshuIozXRSC98WlOl4BHL5WNQwpuRiLk',
    appId: '1:814901029007:ios:cdb03e0004ffcdd42b28fa',
    messagingSenderId: '814901029007',
    projectId: 'auth-app-riverpod',
    storageBucket: 'auth-app-riverpod.appspot.com',
    iosBundleId: 'com.riverpod.auth.authAppRiverpod',
  );
}
